#!/usr/bin/env bash
# =============================================================================
# TCG Tracker — Raspberry Pi Setup Script
# Portable: works for any username, any clone location, any Pi.
# Usage: bash deploy/setup.sh   (from anywhere inside the repo)
# =============================================================================
set -euo pipefail
 
# ── Resolve repo root from script location (works regardless of username/path)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VENV_DIR="$REPO_DIR/venv"
SERVICE_NAME="tcg-tracker"
NGINX_CONF="/etc/nginx/sites-available/$SERVICE_NAME"
CURRENT_USER="$(whoami)"
LOCAL_IP="$(hostname -I | awk '{print $1}')"
 
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
 
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
 
# ── Preflight checks ──────────────────────────────────────────
[[ "$(id -u)" -eq 0 ]] && error "Do not run as root. Run as your normal user (e.g. ryan, pi, ubuntu)."
 
# Verify we're actually inside the repo
[[ -f "$REPO_DIR/main.py" ]] || error "Cannot find main.py in $REPO_DIR — make sure you run this from inside the cloned repo."
[[ -f "$REPO_DIR/requirements.txt" ]] || error "Cannot find requirements.txt in $REPO_DIR."
 
info "TCG Tracker setup starting…"
info "Repo root:    $REPO_DIR"
info "Running as:   $CURRENT_USER"
info "Local IP:     $LOCAL_IP"
 
# ── System packages ───────────────────────────────────────────
info "Installing system dependencies…"
sudo apt-get update -q
sudo apt-get install -y -q \
    python3 python3-pip python3-venv \
    nginx certbot python3-certbot-nginx \
    sqlite3 curl git
 
# ── Python virtual environment ────────────────────────────────
info "Creating Python virtual environment at $VENV_DIR…"
python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip -q
"$VENV_DIR/bin/pip" install -r "$REPO_DIR/requirements.txt" -q
info "Python dependencies installed."
 
# ── Runtime directories ───────────────────────────────────────
mkdir -p "$REPO_DIR/data" "$REPO_DIR/logs"
chmod 700 "$REPO_DIR/data"
info "Created data/ and logs/ directories."
 
# ── .env file ────────────────────────────────────────────────
if [[ ! -f "$REPO_DIR/.env" ]]; then
    cp "$REPO_DIR/.env.example" "$REPO_DIR/.env"
    SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    sed -i "s/change_me_to_a_random_32_byte_hex_string/$SECRET/" "$REPO_DIR/.env"
    warn ".env created from template — EDIT IT before starting the service:"
    warn "  nano $REPO_DIR/.env"
    warn "  → Set ADMIN_PASSWORD, eBay keys, Pushover keys, etc."
else
    info ".env already exists — skipping (delete it to regenerate)."
fi
 
# ── Systemd service (dynamically written — no hardcoded paths) ──
info "Writing systemd service file…"
sudo bash -c "cat > /etc/systemd/system/$SERVICE_NAME.service" << SVCEOF
[Unit]
Description=TCG Price Tracker
After=network.target
 
[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$REPO_DIR
Environment=PATH=$VENV_DIR/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
ExecStart=$VENV_DIR/bin/uvicorn main:app --host 127.0.0.1 --port 8888 --workers 1
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=$REPO_DIR/data $REPO_DIR/logs
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$SERVICE_NAME
 
[Install]
WantedBy=multi-user.target
SVCEOF
 
sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
info "Systemd service installed and enabled."
 
# ── Nginx config (dynamically written — no hardcoded paths) ──
info "Configuring Nginx…"
PUBLIC_IP=$(curl -sf --max-time 5 https://api.ipify.org || echo "YOUR_PUBLIC_IP")
 
# Build the self-signed cert path
SSL_DIR="/etc/ssl/$SERVICE_NAME"
SSL_CERT="$SSL_DIR/selfsigned.crt"
SSL_KEY="$SSL_DIR/selfsigned.key"
 
if [[ ! -f /etc/letsencrypt/live/*/fullchain.pem ]] 2>/dev/null; then
    warn "No Let's Encrypt cert found — generating self-signed cert."
    warn "After pointing a domain at this Pi, upgrade with:"
    warn "  sudo certbot --nginx -d YOUR_DOMAIN"
    sudo mkdir -p "$SSL_DIR"
    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$SSL_KEY" \
        -out    "$SSL_CERT" \
        -subj   "/CN=$LOCAL_IP" 2>/dev/null
    CERT_PATH="$SSL_CERT"
    KEY_PATH="$SSL_KEY"
else
    CERT_PATH="$(ls /etc/letsencrypt/live/*/fullchain.pem | head -1)"
    KEY_PATH="$(ls /etc/letsencrypt/live/*/privkey.pem | head -1)"
    info "Let's Encrypt cert found: $CERT_PATH"
fi
 
sudo bash -c "cat > $NGINX_CONF" << NGINXEOF
# TCG Tracker — generated by setup.sh
# Repo: $REPO_DIR  |  User: $CURRENT_USER
limit_req_zone \$binary_remote_addr zone=general:10m rate=60r/m;
limit_req_zone \$binary_remote_addr zone=login:10m   rate=5r/m;
 
server {
    listen 80;
    server_name _;
    return 301 https://\$host\$request_uri;
}
 
server {
    listen 443 ssl;
    server_name _;
 
    ssl_certificate     $CERT_PATH;
    ssl_certificate_key $KEY_PATH;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
 
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options    "nosniff"                             always;
    add_header X-Frame-Options           "DENY"                                always;
    add_header X-XSS-Protection          "1; mode=block"                       always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin"     always;
 
    location /login {
        limit_req zone=login burst=3 nodelay;
        proxy_pass         http://127.0.0.1:8888;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }
 
    location / {
        limit_req zone=general burst=20 nodelay;
        proxy_pass         http://127.0.0.1:8888;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }
 
    # Static files served directly by Nginx (no hardcoded user path)
    location /static/ {
        alias $REPO_DIR/static/;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
 
    # Block sensitive paths
    location ~ /\.          { deny all; }
    location ~ /\.env       { deny all; }
    location ~ /data/       { deny all; }
    location ~ /logs/       { deny all; }
}
NGINXEOF
 
sudo ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl restart nginx
info "Nginx configured and restarted."
 
# ── Firewall ──────────────────────────────────────────────────
if command -v ufw &>/dev/null; then
    info "Configuring firewall…"
    sudo ufw allow 22/tcp  comment "SSH"
    sudo ufw allow 80/tcp  comment "HTTP → HTTPS redirect"
    sudo ufw allow 443/tcp comment "HTTPS"
    sudo ufw --force enable
    info "Firewall: SSH + HTTP + HTTPS allowed."
fi
 
# ── Certbot auto-renewal cron ─────────────────────────────────
(crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") \
    | sort -u | crontab -
 
# ── Final summary ─────────────────────────────────────────────
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo ""
echo "  Repo:         $REPO_DIR"
echo "  Running as:   $CURRENT_USER"
echo "  Service name: $SERVICE_NAME"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  Step 1 — Edit your credentials${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "    nano $REPO_DIR/.env"
echo ""
echo "  Fill in the following values:"
echo ""
echo "  ADMIN_PASSWORD        → Password to log into the admin panel"
echo "  SECRET_KEY            → Already auto-generated ✓"
echo ""
echo "  EBAY_APP_ID           → From https://developer.ebay.com"
echo "  EBAY_CLIENT_SECRET    → From https://developer.ebay.com"
echo "    (Create a free account → My Apps → Create App → Browse API)"
echo ""
echo "  PRICECHARTING_API_KEY → From https://www.pricecharting.com/api"
echo "    (Free signup, no credit card)"
echo ""
echo "  POKEMONTCG_API_KEY    → From https://pokemontcg.io"
echo "    (Free, optional — raises rate limits)"
echo ""
echo "  PUSHOVER_USER_KEY     → From https://pushover.net (your user key)"
echo "  PUSHOVER_API_TOKEN    → From https://pushover.net/apps/build"
echo "    (Free account + one-time \$5 app licence for iOS/Android)"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  Step 2 — Start the service${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "    sudo systemctl start $SERVICE_NAME"
echo "    sudo journalctl -u $SERVICE_NAME -f    # live logs"
echo "    sudo systemctl status $SERVICE_NAME    # quick status"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  Step 3 — Access the tracker${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  From any device on your home network:"
echo "    https://$LOCAL_IP"
echo ""
echo "  From the internet (after port-forwarding — see Step 4):"
echo "    https://$PUBLIC_IP"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  Step 4 — Port-forwarding (for internet access)${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Log into your router (usually http://192.168.1.1 or http://192.168.0.1)"
echo "  Look for: NAT / Port Forwarding / Virtual Servers / Applications"
echo ""
echo "  Add two rules:"
echo ""
echo "  ┌─────────────────┬──────────────────┬───────────┬──────────┐"
echo "  │ External Port   │ Internal IP      │ Int. Port │ Protocol │"
echo "  ├─────────────────┼──────────────────┼───────────┼──────────┤"
echo "  │ 443             │ $LOCAL_IP        │ 443       │ TCP      │"
echo "  │ 80              │ $LOCAL_IP        │ 80        │ TCP      │"
echo "  └─────────────────┴──────────────────┴───────────┴──────────┘"
echo ""
echo "  Also assign your Pi a static local IP so the rule doesn't break:"
echo "  → In your router: DHCP Reservations / Static Lease"
echo "    Bind MAC address of this Pi to $LOCAL_IP"
echo ""
echo "  Router-specific guides:"
echo "    https://portforward.com  (covers 99% of consumer routers by model)"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  Step 5 — Optional: free HTTPS domain (recommended)${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  A free subdomain removes the browser SSL warning and gives you"
echo "  a memorable URL instead of a bare IP address."
echo ""
echo "  Free dynamic DNS options:"
echo "    DuckDNS  → https://www.duckdns.org  (free, simple, Raspberry Pi friendly)"
echo "    No-IP    → https://www.noip.com     (free tier available)"
echo ""
echo "  Once your domain points at $PUBLIC_IP, run:"
echo "    sudo certbot --nginx -d YOUR_DOMAIN"
echo "  Certbot will auto-renew the cert every 90 days via cron."
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  Deploy on another Pi any time${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "    git clone https://github.com/rgreen1207/TCG-Tracker"
echo "    cd TCG-Tracker && bash deploy/setup.sh"
echo ""
